### ISSUE TITLE
World Capital Cities By Population view error

### ISSUE THREAD

**Issue by ZOulhadj** [checkmate-group/coursework#35]
During my time redesigning the core I saw this error when loading the "view" world_capital_cities_by_population. I am not sure if it was working correctly when @Nero-DevOps created it and therefore, I made a mistake or if it was always broken. Could someone take a closer look at this? It seems like the value `name` does not exist.

```
TypeError: /src/src/views/layouts/tables/world_capital_cities_by_population.pug:9
    7|     tbody
    8|         tr(class="rows")
  > 9|             td= city.Name 
    10|             td= city.Country                   
    11|             td= city.Population

Cannot read properties of undefined (reading 'Name')
    at eval (eval at wrap (/src/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1850:62)
    at template (eval at wrap (/src/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2201:346)
    at Object.exports.renderFile (/src/node_modules/pug/lib/index.js:418:38)
    at Object.exports.renderFile (/src/node_modules/pug/lib/index.js:408:21)
    at View.exports.__express [as engine] (/src/node_modules/pug/lib/index.js:455:11)
    at View.render (/src/node_modules/express/lib/view.js:135:8)
    at tryRender (/src/node_modules/express/lib/application.js:640:10)
    at Function.render (/src/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/src/node_modules/express/lib/response.js:1008:7)
    at Query.onResult (/src/src/routes/app.js:385:17)

```

**Comment by ZOulhadj** [comment]
This has been implicitly solved from another commit and issue. Closing!
